# Generated by Django 5.2.5 on 2025-08-26 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='datasets/')),
                ('n_rows', models.IntegerField(blank=True, null=True)),
                ('n_cols', models.IntegerField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='uploaded', max_length=32)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
