# Generated by Django 5.2.5 on 2025-08-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddataset',
            name='analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadeddataset',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadeddataset',
            name='regression',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
