# Generated by Django 5.2.5 on 2025-08-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_uploadeddataset_analysis_uploadeddataset_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddataset',
            name='ml_classification',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
