# Generated by Django 5.2.5 on 2025-08-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_uploadeddataset_ml_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddataset',
            name='regression_plot',
            field=models.TextField(blank=True, null=True),
        ),
    ]
